name: Daily Email

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        env:
          DAILY_FEED_EMAIL: ${{ secrets.EMAIL_USER }}
          DAILY_FEED_PASSWORD: ${{ secrets.EMAIL_PASS }}
          DAILY_FEED_RECIPIENT: ${{ secrets.EMAIL_USER }}
        run: python main.py
